# 01. Raw Data Audit

## 1. Data Inventory
Inventory the raw CSV files and calculate row counts.

In [1]:
import pandas
import pathlib
import warnings

RAW_DATA_PATH = pathlib.Path("data/raw")
BYTES_TO_MB = 1024 * 1024

csv_files = sorted(list(RAW_DATA_PATH.glob("*.csv")))
inventory_data = []

for file_path in csv_files:
    df = pandas.read_csv(file_path, low_memory=False)
    inventory_data.append({
        "file": file_path.name,
        "size_mb": round(file_path.stat().st_size / BYTES_TO_MB, 2),
        "rows": len(df),
        "cols": len(df.columns),
    })

inventory_df = pandas.DataFrame(inventory_data)

print("DATASET INVENTORY")
display(inventory_df.style.format({"rows": "{:,}", "size_mb": "{:.2f}"}))

total_rows = inventory_df["rows"].sum()
print(f"TOTAL RECORDS: {total_rows:,}")
print(f"TOTAL FILES:   {len(csv_files)}")

DATASET INVENTORY

TOTAL RECORDS: 3,077,538
TOTAL FILES:   11

## 2. Earliest Data Preview
Preview the schema and contents of the earliest file in the dataset.

In [2]:
df_first = pandas.read_csv(csv_files[0], low_memory=False)
print(f"DATA PREVIEW (EARLIEST): {csv_files[0].name}")
display(df_first.head())
print(f"{len(df_first.columns)} Columns: {df_first.columns.tolist()}")

DATA PREVIEW (EARLIEST): policecalls2016.csv

,CDTS,EID,START_DATE,CALL_NUMBER,PRIORITY,REPORT_DATE,OFFENSE_DATE,OFFENSE_TIME,CALLTYPE_CODE,CALL_TYPE,FINAL_DISPO_CODE,FINAL_DISPO,ADDRESS,CITY,STATE
0,20160514222222PD,6235632,5/14/2021 12:00:00 AM,P161350913,3,5/14/2016 12:00:00 AM,5/14/2016 12:00:00 AM,21:23:01,SUSCIR,SUSPICIOUS CIRCUMSTANCES,N,No report required; dispatch r,[2200]-[2200] EASTRIDGE LP,San Jose,CA
1,20160514214406PD,6235633,5/14/2021 12:00:00 AM,P161350914,4,5/14/2016 12:00:00 AM,5/14/2016 12:00:00 AM,21:23:55,415M,"DISTURBANCE, MUSIC",NR,No Response,[1200]-[1300] EDEN AV,San Jose,CA
2,20160514212618PD,6235635,5/14/2021 12:00:00 AM,P161350915,3,5/14/2016 12:00:00 AM,5/14/2016 12:00:00 AM,21:25:39,1033A,"ALARM, AUDIBLE",NR,No Response,[4700]-[4800] MOUNTAIRE PL,San Jose,CA
3,20160514225346PD,6235636,5/14/2021 12:00:00 AM,P161350916,4,5/14/2016 12:00:00 AM,5/14/2016 12:00:00 AM,21:26:34,415M,"DISTURBANCE, MUSIC",NR,No Response,[5700]-[5800] SANTA TERESA BL,San Jose,CA
4,20160514224627PD,6235634,5/14/2021 12:00:00 AM,P161350917,2,5/14/2016 12:00:00 AM,5/14/2016 12:00:00 AM,21:26:48,1181,"VEHICLE ACCIDENT, MINOR INJURI",R,Report taken,[300]-[400] ROYAL AV,San Jose,CA

15 Columns: ['CDTS', 'EID', 'START_DATE', 'CALL_NUMBER', 'PRIORITY', 'REPORT_DATE', 'OFFENSE_DATE', 'OFFENSE_TIME', 'CALLTYPE_CODE', 'CALL_TYPE', 'FINAL_DISPO_CODE', 'FINAL_DISPO', 'ADDRESS', 'CITY', 'STATE']

## 3. Latest Data Preview
Preview the schema and contents of the most recent file in the dataset.

In [3]:
df_last = pandas.read_csv(csv_files[-1], low_memory=False)
print(f"DATA PREVIEW (LATEST): {csv_files[-1].name}")
display(df_last.head())
print(f"{len(df_last.columns)} Columns: {df_last.columns.tolist()}")

DATA PREVIEW (LATEST): policecalls2026.csv

,CDTS,EID,START_DATE,CALL_NUMBER,PRIORITY,REPORT_DATE,OFFENSE_DATE,OFFENSE_TIME,CALLTYPE_CODE,CALL_TYPE,FINAL_DISPO_CODE,FINAL_DISPO,ADDRESS,CITY,STATE,UNHOUSED
0,20260106153549PS,10762827,3/25/2026 12:00:00 AM,P260060516,5,1/6/2026 12:00:00 AM,1/6/2026 12:00:00 AM,14:54:24,22500,PARKING VIOLATION,R,Report taken,[0]-[100] DEL MAR AV,San Jose,CA,NaN
1,20260106170844PS,10762829,3/25/2026 12:00:00 AM,P260060517,2,1/6/2026 12:00:00 AM,1/6/2026 12:00:00 AM,14:56:22,415UNK,"DISTURBANCE, UNKNOWN",U,Unfounded event,[0]-[100] DEL MAR AV,San Jose,CA,NaN
2,20260106155459PS,10762831,3/25/2026 12:00:00 AM,P260060519,5,1/6/2026 12:00:00 AM,1/6/2026 12:00:00 AM,15:00:05,22500,PARKING VIOLATION,R,Report taken,[200]-[300] E ST JOHN ST,San Jose,CA,NaN
3,20260106150059PS,10762832,3/25/2026 12:00:00 AM,P260060520,5,1/6/2026 12:00:00 AM,1/6/2026 12:00:00 AM,15:00:26,1154,SUSPICIOUS VEHICLE,CAN,Canceled,BOREN DR & KELDON DR,San Jose,CA,NaN
4,20260106163123PS,10762833,3/25/2026 12:00:00 AM,P260060521,5,1/6/2026 12:00:00 AM,1/6/2026 12:00:00 AM,15:00:34,1154,SUSPICIOUS VEHICLE,N,No report required; dispatch record only,BOREN DR & KELDON DR,San Jose,CA,T

16 Columns: ['CDTS', 'EID', 'START_DATE', 'CALL_NUMBER', 'PRIORITY', 'REPORT_DATE', 'OFFENSE_DATE', 'OFFENSE_TIME', 'CALLTYPE_CODE', 'CALL_TYPE', 'FINAL_DISPO_CODE', 'FINAL_DISPO', 'ADDRESS', 'CITY', 'STATE', 'UNHOUSED']

## 4. Data Audit
Analyze categorical values, date ranges, and missing data.

In [4]:
warnings.filterwarnings('ignore', category=UserWarning)

def print_wrapped_list(vals, chunk_size=3):
    chunks = [vals[i:i + chunk_size] for i in range(0, len(vals), chunk_size)]
    rows = [", ".join(map(repr, c)) for c in chunks]
    return "[" + ",\n ".join(rows) + "]"

print("COLUMN AUDIT")

# Use the latest df for auditing
df = df_last

for col in df.columns:
    unique_count = df[col].nunique()
    null_count = df[col].isnull().sum()
    
    print(f"\n{col}")
    print(f"  Unique: {unique_count}")
    print(f"  Nulls:  {null_count} ({null_count/len(df)*100:.1f}%)")
    
    if unique_count < 50:
        values = df[col].unique().tolist()
        try:
            values.sort()
        except:
            values = sorted(values, key=lambda x: str(x))
        print(f"  Values: {print_wrapped_list(values)}")
    
    if any(k in col.upper() for k in ['DATE', 'TIME', 'CDTS']):
        try:
            temp_dates = pandas.to_datetime(df[col], errors='coerce', format='mixed')
            if not temp_dates.isna().all():
                print(f"  Range:  {temp_dates.min()} to {temp_dates.max()}")
        except:
            pass

COLUMN AUDIT

CDTS
  Unique: 79711
  Nulls:  0 (0.0%)

EID
  Unique: 79493
  Nulls:  0 (0.0%)

START_DATE
  Unique: 25
  Nulls:  0 (0.0%)
  Values: ['3/25/2026 12:00:00 AM', '3/30/2026 12:00:00 AM', '4/10/2026 12:00:00 AM',
 '4/11/2026 12:00:00 AM', '4/12/2026 12:00:00 AM', '4/13/2026 12:00:00 AM',
 '4/14/2026 12:00:00 AM', '4/15/2026 12:00:00 AM', '4/16/2026 12:00:00 AM',
 '4/17/2026 12:00:00 AM', '4/18/2026 12:00:00 AM', '4/19/2026 12:00:00 AM',
 '4/20/2026 12:00:00 AM', '4/21/2026 12:00:00 AM', '4/22/2026 12:00:00 AM',
 '4/23/2026 12:00:00 AM', '4/24/2026 12:00:00 AM', '4/25/2026 12:00:00 AM',
 '4/26/2026 12:00:00 AM', '4/27/2026 12:00:00 AM', '4/5/2026 12:00:00 AM',
 '4/6/2026 12:00:00 AM', '4/7/2026 12:00:00 AM', '4/8/2026 12:00:00 AM',
 '4/9/2026 12:00:00 AM']
  Range:  2026-03-25 00:00:00 to 2026-04-27 00:00:00

CALL_NUMBER
  Unique: 79582
  Nulls:  0 (0.0%)

PRIORITY
  Unique: 6
  Nulls:  0 (0.0%)
  Values: [1, 2, 3,
 4, 5, 6]

REPORT_DATE
  Unique: 117
  Nulls:  0 (0.0%)
  Range:  2026-01-01 00:00:00 to 2026-04-27 00:00:00

OFFENSE_DATE
  Unique: 117
  Nulls:  0 (0.0%)
  Range:  2026-01-01 00:00:00 to 2026-04-27 00:00:00

OFFENSE_TIME
  Unique: 50628
  Nulls:  0 (0.0%)

  Range:  2026-04-29 00:00:00 to 2026-04-29 23:59:59

CALLTYPE_CODE
  Unique: 185
  Nulls:  0 (0.0%)

CALL_TYPE
  Unique: 182
  Nulls:  0 (0.0%)

FINAL_DISPO_CODE
  Unique: 20
  Nulls:  0 (0.0%)
  Values: [' ', 'A', 'ADV',
 'B', 'C', 'CAN',
 'D', 'DUPNCAN', 'E',
 'F', 'G', 'H',
 'M', 'N', 'O',
 'P', 'R', 'T',
 'U', 'Z']

FINAL_DISPO
  Unique: 17
  Nulls:  0 (0.0%)
  Values: ['Arrest Made', 'Arrest by Warrant', 'Canceled',
 'Courtesy Service/Citizen or agency assist', 'Criminal Citation', 'Field Interview (F.I.) Completed',
 'Gone on Arrival/unable to locate', 'No Disposition', 'No report required; dispatch record only',
 'Prior case, follow-up activity only', 'Report taken', 'Stranded motorist assist',
 'Supplemental report taken', 'Traffic Citation Issued, Hazardous Violation', 'Traffic Citation Issued, Non-Hazardous Violation',
 'Turned over To (TOT)', 'Unfounded event']

ADDRESS
  Unique: 18548
  Nulls:  2487 (2.7%)

CITY
  Unique: 1
  Nulls:  0 (0.0%)
  Values: ['San Jose']

STATE
  Unique: 1
  Nulls:  0 (0.0%)
  Values: ['CA']

UNHOUSED
  Unique: 1
  Nulls:  87697 (95.4%)
  Values: ['T', nan]